"""Added account table

Revision ID: 478d8e9d742f
Revises: 
Create Date: 2022-11-04 19:48:16.547417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '478d8e9d742f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gap_analysis_questions',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=True),
    sa.Column('questionId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=False),
    sa.Column('questionMetaData', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('removalDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removedBy', sa.String(length=50), nullable=True),
    sa.Column('removalRemarks', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('questionId'),
    schema='a'
    )
    op.create_index(op.f('ix_district_schema_gap_analysis_questions_createdBy'), 'gap_analysis_questions', ['createdBy'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_gap_analysis_questions_isRemoved'), 'gap_analysis_questions', ['isRemoved'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_gap_analysis_questions_questionId'), 'gap_analysis_questions', ['questionId'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_gap_analysis_questions_removedBy'), 'gap_analysis_questions', ['removedBy'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_gap_analysis_questions_schoolShortName'), 'gap_analysis_questions', ['schoolShortName'], unique=False, schema='a')
    op.create_table('question_category',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('categoryId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=True),
    sa.Column('categoryName', sa.String(length=50), nullable=False),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('isRequired', sa.Boolean(), nullable=True),
    sa.Column('removalDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removedBy', sa.String(length=50), nullable=True),
    sa.Column('removalRemarks', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('categoryId'),
    schema='a'
    )
    op.create_index(op.f('ix_district_schema_question_category_categoryId'), 'question_category', ['categoryId'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_question_category_createdBy'), 'question_category', ['createdBy'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_question_category_isRemoved'), 'question_category', ['isRemoved'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_question_category_removedBy'), 'question_category', ['removedBy'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_question_category_schoolShortName'), 'question_category', ['schoolShortName'], unique=False, schema='a')
    op.create_table('question_section',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('sectionId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=True),
    sa.Column('sectionName', sa.String(length=500), nullable=False),
    sa.Column('categoryId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('removalDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removedBy', sa.String(length=50), nullable=True),
    sa.Column('removalRemarks', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['district_schema.question_category.categoryId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sectionId'),
    schema='a'
    )
    op.create_index(op.f('ix_district_schema_question_section_categoryId'), 'question_section', ['categoryId'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_question_section_createdBy'), 'question_section', ['createdBy'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_question_section_isRemoved'), 'question_section', ['isRemoved'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_question_section_removedBy'), 'question_section', ['removedBy'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_question_section_schoolShortName'), 'question_section', ['schoolShortName'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_question_section_sectionId'), 'question_section', ['sectionId'], unique=False, schema='a')
    op.create_table('safety_assessment_questions',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=True),
    sa.Column('questionId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('questionNumber', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=False),
    sa.Column('weightedCriticality', sa.Integer(), nullable=False),
    sa.Column('sectionId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('additionalInfo', sa.String(length=1000), nullable=True),
    sa.Column('questionMetaData', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('removalDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removedBy', sa.String(length=50), nullable=True),
    sa.Column('removalRemarks', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sectionId'], ['district_schema.question_section.sectionId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('questionId'),
    schema='a'
    )
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_createdBy'), 'safety_assessment_questions', ['createdBy'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_isRemoved'), 'safety_assessment_questions', ['isRemoved'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_questionId'), 'safety_assessment_questions', ['questionId'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_questionNumber'), 'safety_assessment_questions', ['questionNumber'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_removedBy'), 'safety_assessment_questions', ['removedBy'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_schoolShortName'), 'safety_assessment_questions', ['schoolShortName'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_sectionId'), 'safety_assessment_questions', ['sectionId'], unique=False, schema='a')
    op.create_table('school_data',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=False),
    sa.Column('schoolType', sa.String(length=30), nullable=False),
    sa.Column('charterSchool', sa.Boolean(), nullable=True),
    sa.Column('privateSchool', sa.Boolean(), nullable=True),
    sa.Column('cityName', sa.String(length=50), nullable=False),
    sa.Column('isAcademy', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schoolShortName'),
    schema='a'
    )
    op.create_index(op.f('ix_district_schema_school_data_charterSchool'), 'school_data', ['charterSchool'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_data_cityName'), 'school_data', ['cityName'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_data_isAcademy'), 'school_data', ['isAcademy'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_data_isRemoved'), 'school_data', ['isRemoved'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_data_privateSchool'), 'school_data', ['privateSchool'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_data_schoolShortName'), 'school_data', ['schoolShortName'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_data_schoolType'), 'school_data', ['schoolType'], unique=False, schema='a')
    op.create_table('school_safety_assessment_answers',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('answerId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('questionId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('assessmentId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('assessmentScore', sa.Integer(), nullable=True),
    sa.Column('supportText', sa.String(length=1000), nullable=True),
    sa.Column('answeredBy', sa.String(length=50), nullable=False),
    sa.Column('gapAnalysisAnswers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['assessmentId'], ['district_schema.school_safety_assessments.assessmentId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questionId'], ['district_schema.safety_assessment_questions.questionId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answerId'),
    schema='a'
    )
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_answerId'), 'school_safety_assessment_answers', ['answerId'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_answeredBy'), 'school_safety_assessment_answers', ['answeredBy'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_assessmentScore'), 'school_safety_assessment_answers', ['assessmentScore'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_assessmentId'), 'school_safety_assessment_answers', ['assessmentId'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_isRemoved'), 'school_safety_assessment_answers', ['isRemoved'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_questionId'), 'school_safety_assessment_answers', ['questionId'], unique=False, schema='a')
    op.create_table('school_safety_assessments',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('assessmentId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=True),
    sa.Column('academicYear', sa.String(length=12), nullable=False),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('modifiedBy', sa.String(length=50), nullable=True),
    sa.Column('approvedBy', sa.String(length=50), nullable=True),
    sa.Column('statusChangeDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approvalState', sa.String(length=25), nullable=False),
    sa.Column('removalDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removedBy', sa.String(length=50), nullable=True),
    sa.Column('removalRemarks', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessmentId'),
    schema='a'
    )
    op.create_index(op.f('ix_district_schema_school_safety_assessments_academicYear'), 'school_safety_assessments', ['academicYear'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_approvalState'), 'school_safety_assessments', ['approvalState'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_approvedBy'), 'school_safety_assessments', ['approvedBy'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_assessmentId'), 'school_safety_assessments', ['assessmentId'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_createdBy'), 'school_safety_assessments', ['createdBy'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_isRemoved'), 'school_safety_assessments', ['isRemoved'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_modifiedBy'), 'school_safety_assessments', ['modifiedBy'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_removedBy'), 'school_safety_assessments', ['removedBy'], unique=False, schema='a')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_schoolShortName'), 'school_safety_assessments', ['schoolShortName'], unique=False, schema='a')
    op.create_table('gap_analysis_questions',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=True),
    sa.Column('questionId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=False),
    sa.Column('questionMetaData', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('removalDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removedBy', sa.String(length=50), nullable=True),
    sa.Column('removalRemarks', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('questionId'),
    schema='b'
    )
    op.create_index(op.f('ix_district_schema_gap_analysis_questions_createdBy'), 'gap_analysis_questions', ['createdBy'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_gap_analysis_questions_isRemoved'), 'gap_analysis_questions', ['isRemoved'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_gap_analysis_questions_questionId'), 'gap_analysis_questions', ['questionId'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_gap_analysis_questions_removedBy'), 'gap_analysis_questions', ['removedBy'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_gap_analysis_questions_schoolShortName'), 'gap_analysis_questions', ['schoolShortName'], unique=False, schema='b')
    op.create_table('question_category',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('categoryId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=True),
    sa.Column('categoryName', sa.String(length=50), nullable=False),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('isRequired', sa.Boolean(), nullable=True),
    sa.Column('removalDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removedBy', sa.String(length=50), nullable=True),
    sa.Column('removalRemarks', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('categoryId'),
    schema='b'
    )
    op.create_index(op.f('ix_district_schema_question_category_categoryId'), 'question_category', ['categoryId'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_question_category_createdBy'), 'question_category', ['createdBy'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_question_category_isRemoved'), 'question_category', ['isRemoved'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_question_category_removedBy'), 'question_category', ['removedBy'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_question_category_schoolShortName'), 'question_category', ['schoolShortName'], unique=False, schema='b')
    op.create_table('question_section',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('sectionId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=True),
    sa.Column('sectionName', sa.String(length=500), nullable=False),
    sa.Column('categoryId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('removalDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removedBy', sa.String(length=50), nullable=True),
    sa.Column('removalRemarks', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['district_schema.question_category.categoryId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sectionId'),
    schema='b'
    )
    op.create_index(op.f('ix_district_schema_question_section_categoryId'), 'question_section', ['categoryId'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_question_section_createdBy'), 'question_section', ['createdBy'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_question_section_isRemoved'), 'question_section', ['isRemoved'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_question_section_removedBy'), 'question_section', ['removedBy'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_question_section_schoolShortName'), 'question_section', ['schoolShortName'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_question_section_sectionId'), 'question_section', ['sectionId'], unique=False, schema='b')
    op.create_table('safety_assessment_questions',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=True),
    sa.Column('questionId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('questionNumber', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=False),
    sa.Column('weightedCriticality', sa.Integer(), nullable=False),
    sa.Column('sectionId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('additionalInfo', sa.String(length=1000), nullable=True),
    sa.Column('questionMetaData', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('removalDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removedBy', sa.String(length=50), nullable=True),
    sa.Column('removalRemarks', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sectionId'], ['district_schema.question_section.sectionId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('questionId'),
    schema='b'
    )
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_createdBy'), 'safety_assessment_questions', ['createdBy'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_isRemoved'), 'safety_assessment_questions', ['isRemoved'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_questionId'), 'safety_assessment_questions', ['questionId'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_questionNumber'), 'safety_assessment_questions', ['questionNumber'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_removedBy'), 'safety_assessment_questions', ['removedBy'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_schoolShortName'), 'safety_assessment_questions', ['schoolShortName'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_sectionId'), 'safety_assessment_questions', ['sectionId'], unique=False, schema='b')
    op.create_table('school_data',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=False),
    sa.Column('schoolType', sa.String(length=30), nullable=False),
    sa.Column('charterSchool', sa.Boolean(), nullable=True),
    sa.Column('privateSchool', sa.Boolean(), nullable=True),
    sa.Column('cityName', sa.String(length=50), nullable=False),
    sa.Column('isAcademy', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schoolShortName'),
    schema='b'
    )
    op.create_index(op.f('ix_district_schema_school_data_charterSchool'), 'school_data', ['charterSchool'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_data_cityName'), 'school_data', ['cityName'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_data_isAcademy'), 'school_data', ['isAcademy'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_data_isRemoved'), 'school_data', ['isRemoved'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_data_privateSchool'), 'school_data', ['privateSchool'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_data_schoolShortName'), 'school_data', ['schoolShortName'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_data_schoolType'), 'school_data', ['schoolType'], unique=False, schema='b')
    op.create_table('school_safety_assessment_answers',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('answerId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('questionId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('assessmentId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('assessmentScore', sa.Integer(), nullable=True),
    sa.Column('supportText', sa.String(length=1000), nullable=True),
    sa.Column('answeredBy', sa.String(length=50), nullable=False),
    sa.Column('gapAnalysisAnswers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['assessmentId'], ['district_schema.school_safety_assessments.assessmentId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questionId'], ['district_schema.safety_assessment_questions.questionId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answerId'),
    schema='b'
    )
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_answerId'), 'school_safety_assessment_answers', ['answerId'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_answeredBy'), 'school_safety_assessment_answers', ['answeredBy'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_assessmentScore'), 'school_safety_assessment_answers', ['assessmentScore'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_assessmentId'), 'school_safety_assessment_answers', ['assessmentId'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_isRemoved'), 'school_safety_assessment_answers', ['isRemoved'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_questionId'), 'school_safety_assessment_answers', ['questionId'], unique=False, schema='b')
    op.create_table('school_safety_assessments',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('assessmentId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=True),
    sa.Column('academicYear', sa.String(length=12), nullable=False),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('modifiedBy', sa.String(length=50), nullable=True),
    sa.Column('approvedBy', sa.String(length=50), nullable=True),
    sa.Column('statusChangeDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approvalState', sa.String(length=25), nullable=False),
    sa.Column('removalDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removedBy', sa.String(length=50), nullable=True),
    sa.Column('removalRemarks', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessmentId'),
    schema='b'
    )
    op.create_index(op.f('ix_district_schema_school_safety_assessments_academicYear'), 'school_safety_assessments', ['academicYear'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_approvalState'), 'school_safety_assessments', ['approvalState'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_approvedBy'), 'school_safety_assessments', ['approvedBy'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_assessmentId'), 'school_safety_assessments', ['assessmentId'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_createdBy'), 'school_safety_assessments', ['createdBy'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_isRemoved'), 'school_safety_assessments', ['isRemoved'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_modifiedBy'), 'school_safety_assessments', ['modifiedBy'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_removedBy'), 'school_safety_assessments', ['removedBy'], unique=False, schema='b')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_schoolShortName'), 'school_safety_assessments', ['schoolShortName'], unique=False, schema='b')
    op.create_table('gap_analysis_questions',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=True),
    sa.Column('questionId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=False),
    sa.Column('questionMetaData', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('removalDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removedBy', sa.String(length=50), nullable=True),
    sa.Column('removalRemarks', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('questionId'),
    schema='c'
    )
    op.create_index(op.f('ix_district_schema_gap_analysis_questions_createdBy'), 'gap_analysis_questions', ['createdBy'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_gap_analysis_questions_isRemoved'), 'gap_analysis_questions', ['isRemoved'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_gap_analysis_questions_questionId'), 'gap_analysis_questions', ['questionId'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_gap_analysis_questions_removedBy'), 'gap_analysis_questions', ['removedBy'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_gap_analysis_questions_schoolShortName'), 'gap_analysis_questions', ['schoolShortName'], unique=False, schema='c')
    op.create_table('question_category',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('categoryId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=True),
    sa.Column('categoryName', sa.String(length=50), nullable=False),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('isRequired', sa.Boolean(), nullable=True),
    sa.Column('removalDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removedBy', sa.String(length=50), nullable=True),
    sa.Column('removalRemarks', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('categoryId'),
    schema='c'
    )
    op.create_index(op.f('ix_district_schema_question_category_categoryId'), 'question_category', ['categoryId'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_question_category_createdBy'), 'question_category', ['createdBy'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_question_category_isRemoved'), 'question_category', ['isRemoved'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_question_category_removedBy'), 'question_category', ['removedBy'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_question_category_schoolShortName'), 'question_category', ['schoolShortName'], unique=False, schema='c')
    op.create_table('question_section',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('sectionId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=True),
    sa.Column('sectionName', sa.String(length=500), nullable=False),
    sa.Column('categoryId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('removalDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removedBy', sa.String(length=50), nullable=True),
    sa.Column('removalRemarks', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['district_schema.question_category.categoryId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sectionId'),
    schema='c'
    )
    op.create_index(op.f('ix_district_schema_question_section_categoryId'), 'question_section', ['categoryId'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_question_section_createdBy'), 'question_section', ['createdBy'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_question_section_isRemoved'), 'question_section', ['isRemoved'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_question_section_removedBy'), 'question_section', ['removedBy'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_question_section_schoolShortName'), 'question_section', ['schoolShortName'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_question_section_sectionId'), 'question_section', ['sectionId'], unique=False, schema='c')
    op.create_table('safety_assessment_questions',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=True),
    sa.Column('questionId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('questionNumber', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=False),
    sa.Column('weightedCriticality', sa.Integer(), nullable=False),
    sa.Column('sectionId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('additionalInfo', sa.String(length=1000), nullable=True),
    sa.Column('questionMetaData', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('removalDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removedBy', sa.String(length=50), nullable=True),
    sa.Column('removalRemarks', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sectionId'], ['district_schema.question_section.sectionId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('questionId'),
    schema='c'
    )
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_createdBy'), 'safety_assessment_questions', ['createdBy'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_isRemoved'), 'safety_assessment_questions', ['isRemoved'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_questionId'), 'safety_assessment_questions', ['questionId'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_questionNumber'), 'safety_assessment_questions', ['questionNumber'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_removedBy'), 'safety_assessment_questions', ['removedBy'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_schoolShortName'), 'safety_assessment_questions', ['schoolShortName'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_safety_assessment_questions_sectionId'), 'safety_assessment_questions', ['sectionId'], unique=False, schema='c')
    op.create_table('school_data',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=False),
    sa.Column('schoolType', sa.String(length=30), nullable=False),
    sa.Column('charterSchool', sa.Boolean(), nullable=True),
    sa.Column('privateSchool', sa.Boolean(), nullable=True),
    sa.Column('cityName', sa.String(length=50), nullable=False),
    sa.Column('isAcademy', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schoolShortName'),
    schema='c'
    )
    op.create_index(op.f('ix_district_schema_school_data_charterSchool'), 'school_data', ['charterSchool'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_data_cityName'), 'school_data', ['cityName'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_data_isAcademy'), 'school_data', ['isAcademy'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_data_isRemoved'), 'school_data', ['isRemoved'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_data_privateSchool'), 'school_data', ['privateSchool'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_data_schoolShortName'), 'school_data', ['schoolShortName'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_data_schoolType'), 'school_data', ['schoolType'], unique=False, schema='c')
    op.create_table('school_safety_assessment_answers',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('answerId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('questionId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('assessmentId', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('assessmentScore', sa.Integer(), nullable=True),
    sa.Column('supportText', sa.String(length=1000), nullable=True),
    sa.Column('answeredBy', sa.String(length=50), nullable=False),
    sa.Column('gapAnalysisAnswers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['assessmentId'], ['district_schema.school_safety_assessments.assessmentId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questionId'], ['district_schema.safety_assessment_questions.questionId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answerId'),
    schema='c'
    )
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_answerId'), 'school_safety_assessment_answers', ['answerId'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_answeredBy'), 'school_safety_assessment_answers', ['answeredBy'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_assessmentScore'), 'school_safety_assessment_answers', ['assessmentScore'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_assessmentId'), 'school_safety_assessment_answers', ['assessmentId'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_isRemoved'), 'school_safety_assessment_answers', ['isRemoved'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_safety_assessment_answers_questionId'), 'school_safety_assessment_answers', ['questionId'], unique=False, schema='c')
    op.create_table('school_safety_assessments',
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isRemoved', sa.Boolean(), nullable=False),
    sa.Column('assessmentId', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('schoolShortName', sa.String(length=20), nullable=True),
    sa.Column('academicYear', sa.String(length=12), nullable=False),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('modifiedBy', sa.String(length=50), nullable=True),
    sa.Column('approvedBy', sa.String(length=50), nullable=True),
    sa.Column('statusChangeDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approvalState', sa.String(length=25), nullable=False),
    sa.Column('removalDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removedBy', sa.String(length=50), nullable=True),
    sa.Column('removalRemarks', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['schoolShortName'], ['school.schoolShortName'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessmentId'),
    schema='c'
    )
    op.create_index(op.f('ix_district_schema_school_safety_assessments_academicYear'), 'school_safety_assessments', ['academicYear'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_approvalState'), 'school_safety_assessments', ['approvalState'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_approvedBy'), 'school_safety_assessments', ['approvedBy'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_assessmentId'), 'school_safety_assessments', ['assessmentId'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_createdBy'), 'school_safety_assessments', ['createdBy'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_isRemoved'), 'school_safety_assessments', ['isRemoved'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_modifiedBy'), 'school_safety_assessments', ['modifiedBy'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_removedBy'), 'school_safety_assessments', ['removedBy'], unique=False, schema='c')
    op.create_index(op.f('ix_district_schema_school_safety_assessments_schoolShortName'), 'school_safety_assessments', ['schoolShortName'], unique=False, schema='c')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_schoolShortName'), table_name='school_safety_assessments', schema='c')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_removedBy'), table_name='school_safety_assessments', schema='c')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_modifiedBy'), table_name='school_safety_assessments', schema='c')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_isRemoved'), table_name='school_safety_assessments', schema='c')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_createdBy'), table_name='school_safety_assessments', schema='c')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_assessmentId'), table_name='school_safety_assessments', schema='c')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_approvedBy'), table_name='school_safety_assessments', schema='c')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_approvalState'), table_name='school_safety_assessments', schema='c')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_academicYear'), table_name='school_safety_assessments', schema='c')
    op.drop_table('school_safety_assessments', schema='c')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_questionId'), table_name='school_safety_assessment_answers', schema='c')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_isRemoved'), table_name='school_safety_assessment_answers', schema='c')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_assessmentId'), table_name='school_safety_assessment_answers', schema='c')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_assessmentScore'), table_name='school_safety_assessment_answers', schema='c')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_answeredBy'), table_name='school_safety_assessment_answers', schema='c')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_answerId'), table_name='school_safety_assessment_answers', schema='c')
    op.drop_table('school_safety_assessment_answers', schema='c')
    op.drop_index(op.f('ix_district_schema_school_data_schoolType'), table_name='school_data', schema='c')
    op.drop_index(op.f('ix_district_schema_school_data_schoolShortName'), table_name='school_data', schema='c')
    op.drop_index(op.f('ix_district_schema_school_data_privateSchool'), table_name='school_data', schema='c')
    op.drop_index(op.f('ix_district_schema_school_data_isRemoved'), table_name='school_data', schema='c')
    op.drop_index(op.f('ix_district_schema_school_data_isAcademy'), table_name='school_data', schema='c')
    op.drop_index(op.f('ix_district_schema_school_data_cityName'), table_name='school_data', schema='c')
    op.drop_index(op.f('ix_district_schema_school_data_charterSchool'), table_name='school_data', schema='c')
    op.drop_table('school_data', schema='c')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_sectionId'), table_name='safety_assessment_questions', schema='c')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_schoolShortName'), table_name='safety_assessment_questions', schema='c')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_removedBy'), table_name='safety_assessment_questions', schema='c')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_questionNumber'), table_name='safety_assessment_questions', schema='c')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_questionId'), table_name='safety_assessment_questions', schema='c')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_isRemoved'), table_name='safety_assessment_questions', schema='c')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_createdBy'), table_name='safety_assessment_questions', schema='c')
    op.drop_table('safety_assessment_questions', schema='c')
    op.drop_index(op.f('ix_district_schema_question_section_sectionId'), table_name='question_section', schema='c')
    op.drop_index(op.f('ix_district_schema_question_section_schoolShortName'), table_name='question_section', schema='c')
    op.drop_index(op.f('ix_district_schema_question_section_removedBy'), table_name='question_section', schema='c')
    op.drop_index(op.f('ix_district_schema_question_section_isRemoved'), table_name='question_section', schema='c')
    op.drop_index(op.f('ix_district_schema_question_section_createdBy'), table_name='question_section', schema='c')
    op.drop_index(op.f('ix_district_schema_question_section_categoryId'), table_name='question_section', schema='c')
    op.drop_table('question_section', schema='c')
    op.drop_index(op.f('ix_district_schema_question_category_schoolShortName'), table_name='question_category', schema='c')
    op.drop_index(op.f('ix_district_schema_question_category_removedBy'), table_name='question_category', schema='c')
    op.drop_index(op.f('ix_district_schema_question_category_isRemoved'), table_name='question_category', schema='c')
    op.drop_index(op.f('ix_district_schema_question_category_createdBy'), table_name='question_category', schema='c')
    op.drop_index(op.f('ix_district_schema_question_category_categoryId'), table_name='question_category', schema='c')
    op.drop_table('question_category', schema='c')
    op.drop_index(op.f('ix_district_schema_gap_analysis_questions_schoolShortName'), table_name='gap_analysis_questions', schema='c')
    op.drop_index(op.f('ix_district_schema_gap_analysis_questions_removedBy'), table_name='gap_analysis_questions', schema='c')
    op.drop_index(op.f('ix_district_schema_gap_analysis_questions_questionId'), table_name='gap_analysis_questions', schema='c')
    op.drop_index(op.f('ix_district_schema_gap_analysis_questions_isRemoved'), table_name='gap_analysis_questions', schema='c')
    op.drop_index(op.f('ix_district_schema_gap_analysis_questions_createdBy'), table_name='gap_analysis_questions', schema='c')
    op.drop_table('gap_analysis_questions', schema='c')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_schoolShortName'), table_name='school_safety_assessments', schema='b')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_removedBy'), table_name='school_safety_assessments', schema='b')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_modifiedBy'), table_name='school_safety_assessments', schema='b')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_isRemoved'), table_name='school_safety_assessments', schema='b')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_createdBy'), table_name='school_safety_assessments', schema='b')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_assessmentId'), table_name='school_safety_assessments', schema='b')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_approvedBy'), table_name='school_safety_assessments', schema='b')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_approvalState'), table_name='school_safety_assessments', schema='b')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_academicYear'), table_name='school_safety_assessments', schema='b')
    op.drop_table('school_safety_assessments', schema='b')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_questionId'), table_name='school_safety_assessment_answers', schema='b')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_isRemoved'), table_name='school_safety_assessment_answers', schema='b')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_assessmentId'), table_name='school_safety_assessment_answers', schema='b')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_assessmentScore'), table_name='school_safety_assessment_answers', schema='b')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_answeredBy'), table_name='school_safety_assessment_answers', schema='b')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_answerId'), table_name='school_safety_assessment_answers', schema='b')
    op.drop_table('school_safety_assessment_answers', schema='b')
    op.drop_index(op.f('ix_district_schema_school_data_schoolType'), table_name='school_data', schema='b')
    op.drop_index(op.f('ix_district_schema_school_data_schoolShortName'), table_name='school_data', schema='b')
    op.drop_index(op.f('ix_district_schema_school_data_privateSchool'), table_name='school_data', schema='b')
    op.drop_index(op.f('ix_district_schema_school_data_isRemoved'), table_name='school_data', schema='b')
    op.drop_index(op.f('ix_district_schema_school_data_isAcademy'), table_name='school_data', schema='b')
    op.drop_index(op.f('ix_district_schema_school_data_cityName'), table_name='school_data', schema='b')
    op.drop_index(op.f('ix_district_schema_school_data_charterSchool'), table_name='school_data', schema='b')
    op.drop_table('school_data', schema='b')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_sectionId'), table_name='safety_assessment_questions', schema='b')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_schoolShortName'), table_name='safety_assessment_questions', schema='b')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_removedBy'), table_name='safety_assessment_questions', schema='b')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_questionNumber'), table_name='safety_assessment_questions', schema='b')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_questionId'), table_name='safety_assessment_questions', schema='b')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_isRemoved'), table_name='safety_assessment_questions', schema='b')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_createdBy'), table_name='safety_assessment_questions', schema='b')
    op.drop_table('safety_assessment_questions', schema='b')
    op.drop_index(op.f('ix_district_schema_question_section_sectionId'), table_name='question_section', schema='b')
    op.drop_index(op.f('ix_district_schema_question_section_schoolShortName'), table_name='question_section', schema='b')
    op.drop_index(op.f('ix_district_schema_question_section_removedBy'), table_name='question_section', schema='b')
    op.drop_index(op.f('ix_district_schema_question_section_isRemoved'), table_name='question_section', schema='b')
    op.drop_index(op.f('ix_district_schema_question_section_createdBy'), table_name='question_section', schema='b')
    op.drop_index(op.f('ix_district_schema_question_section_categoryId'), table_name='question_section', schema='b')
    op.drop_table('question_section', schema='b')
    op.drop_index(op.f('ix_district_schema_question_category_schoolShortName'), table_name='question_category', schema='b')
    op.drop_index(op.f('ix_district_schema_question_category_removedBy'), table_name='question_category', schema='b')
    op.drop_index(op.f('ix_district_schema_question_category_isRemoved'), table_name='question_category', schema='b')
    op.drop_index(op.f('ix_district_schema_question_category_createdBy'), table_name='question_category', schema='b')
    op.drop_index(op.f('ix_district_schema_question_category_categoryId'), table_name='question_category', schema='b')
    op.drop_table('question_category', schema='b')
    op.drop_index(op.f('ix_district_schema_gap_analysis_questions_schoolShortName'), table_name='gap_analysis_questions', schema='b')
    op.drop_index(op.f('ix_district_schema_gap_analysis_questions_removedBy'), table_name='gap_analysis_questions', schema='b')
    op.drop_index(op.f('ix_district_schema_gap_analysis_questions_questionId'), table_name='gap_analysis_questions', schema='b')
    op.drop_index(op.f('ix_district_schema_gap_analysis_questions_isRemoved'), table_name='gap_analysis_questions', schema='b')
    op.drop_index(op.f('ix_district_schema_gap_analysis_questions_createdBy'), table_name='gap_analysis_questions', schema='b')
    op.drop_table('gap_analysis_questions', schema='b')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_schoolShortName'), table_name='school_safety_assessments', schema='a')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_removedBy'), table_name='school_safety_assessments', schema='a')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_modifiedBy'), table_name='school_safety_assessments', schema='a')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_isRemoved'), table_name='school_safety_assessments', schema='a')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_createdBy'), table_name='school_safety_assessments', schema='a')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_assessmentId'), table_name='school_safety_assessments', schema='a')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_approvedBy'), table_name='school_safety_assessments', schema='a')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_approvalState'), table_name='school_safety_assessments', schema='a')
    op.drop_index(op.f('ix_district_schema_school_safety_assessments_academicYear'), table_name='school_safety_assessments', schema='a')
    op.drop_table('school_safety_assessments', schema='a')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_questionId'), table_name='school_safety_assessment_answers', schema='a')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_isRemoved'), table_name='school_safety_assessment_answers', schema='a')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_assessmentId'), table_name='school_safety_assessment_answers', schema='a')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_assessmentScore'), table_name='school_safety_assessment_answers', schema='a')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_answeredBy'), table_name='school_safety_assessment_answers', schema='a')
    op.drop_index(op.f('ix_district_schema_school_safety_assessment_answers_answerId'), table_name='school_safety_assessment_answers', schema='a')
    op.drop_table('school_safety_assessment_answers', schema='a')
    op.drop_index(op.f('ix_district_schema_school_data_schoolType'), table_name='school_data', schema='a')
    op.drop_index(op.f('ix_district_schema_school_data_schoolShortName'), table_name='school_data', schema='a')
    op.drop_index(op.f('ix_district_schema_school_data_privateSchool'), table_name='school_data', schema='a')
    op.drop_index(op.f('ix_district_schema_school_data_isRemoved'), table_name='school_data', schema='a')
    op.drop_index(op.f('ix_district_schema_school_data_isAcademy'), table_name='school_data', schema='a')
    op.drop_index(op.f('ix_district_schema_school_data_cityName'), table_name='school_data', schema='a')
    op.drop_index(op.f('ix_district_schema_school_data_charterSchool'), table_name='school_data', schema='a')
    op.drop_table('school_data', schema='a')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_sectionId'), table_name='safety_assessment_questions', schema='a')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_schoolShortName'), table_name='safety_assessment_questions', schema='a')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_removedBy'), table_name='safety_assessment_questions', schema='a')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_questionNumber'), table_name='safety_assessment_questions', schema='a')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_questionId'), table_name='safety_assessment_questions', schema='a')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_isRemoved'), table_name='safety_assessment_questions', schema='a')
    op.drop_index(op.f('ix_district_schema_safety_assessment_questions_createdBy'), table_name='safety_assessment_questions', schema='a')
    op.drop_table('safety_assessment_questions', schema='a')
    op.drop_index(op.f('ix_district_schema_question_section_sectionId'), table_name='question_section', schema='a')
    op.drop_index(op.f('ix_district_schema_question_section_schoolShortName'), table_name='question_section', schema='a')
    op.drop_index(op.f('ix_district_schema_question_section_removedBy'), table_name='question_section', schema='a')
    op.drop_index(op.f('ix_district_schema_question_section_isRemoved'), table_name='question_section', schema='a')
    op.drop_index(op.f('ix_district_schema_question_section_createdBy'), table_name='question_section', schema='a')
    op.drop_index(op.f('ix_district_schema_question_section_categoryId'), table_name='question_section', schema='a')
    op.drop_table('question_section', schema='a')
    op.drop_index(op.f('ix_district_schema_question_category_schoolShortName'), table_name='question_category', schema='a')
    op.drop_index(op.f('ix_district_schema_question_category_removedBy'), table_name='question_category', schema='a')
    op.drop_index(op.f('ix_district_schema_question_category_isRemoved'), table_name='question_category', schema='a')
    op.drop_index(op.f('ix_district_schema_question_category_createdBy'), table_name='question_category', schema='a')
    op.drop_index(op.f('ix_district_schema_question_category_categoryId'), table_name='question_category', schema='a')
    op.drop_table('question_category', schema='a')
    op.drop_index(op.f('ix_district_schema_gap_analysis_questions_schoolShortName'), table_name='gap_analysis_questions', schema='a')
    op.drop_index(op.f('ix_district_schema_gap_analysis_questions_removedBy'), table_name='gap_analysis_questions', schema='a')
    op.drop_index(op.f('ix_district_schema_gap_analysis_questions_questionId'), table_name='gap_analysis_questions', schema='a')
    op.drop_index(op.f('ix_district_schema_gap_analysis_questions_isRemoved'), table_name='gap_analysis_questions', schema='a')
    op.drop_index(op.f('ix_district_schema_gap_analysis_questions_createdBy'), table_name='gap_analysis_questions', schema='a')
    op.drop_table('gap_analysis_questions', schema='a')
    # ### end Alembic commands ###
